### ISSUE TITLE
Feature: New regionalised  MFD targets for subduction inversion

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#103]
SRM team want to run experiments setting traget MFDs for the Hikurangi and Kermadec regions independently.

requires:
 - [ ] region defintions lat/lon strings for the two regions 
 - [ ] API changes to support multiple MFD settings

**Comment by chrisbc** [comment]
@voj maybe we could generalise the Gateway API / configuration to take a mapping of REGION_ENUM -> MFD config? I need to look into the impact of this in Toshi-land .

**Comment by chrisbc** [comment]
@mcg-gns not sure whether this is still in scope. moving priority to  Todo for now

**Comment by chrisdicaprio** [comment]
close as dup
