### ISSUE TITLE
Feature: migrate inversion constraints to new UncertaintyWeighted form

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#124]
Kevin has added many  inversion & reporting improvements that rely on this new form of the constraints. For this approach every Inversion Constraint must use UncertaintyWeighting and have uncertainty data setup.

We will need to keep the current Inversion Constraint configuration and be able to use both this and the new UncertaintyWeighted going forward. 

**Done when:**
 - [x] set up new  MFD constraints and add API support
 - [x] set up new slip constraints and add API support
 - [x] set up new paleo constraints and add API support
 - [x] setup/acquire initial uncertainty data for above
 - [x] run inversion using java gateway runner
 - [x] run diagnostic reports and identify new report sections
 - [x] review with SRM science group

**Comment by voj** [comment]
- paleo comes with built-in uncertainty
- MFD constraints uncertainty can be enabled by calling `setUncertaintyWeightedMFDWeights` on the runner (both crustal and subduction)
- slip constraints uncertainty can be enabled by calling `setSlipRateUncertaintyConstraint` on the runner (both crustal and subduction)

Note:

- the signature of `setSlipRateUncertaintyConstraint` has changed and does to take a weightingType anymore.
- it is illegal to call these uncertainty settings alongside their normal counterparts.

**Comment by voj** [comment]
merged
