### ISSUE TITLE
Fix hazard background

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#127]
This bug was exposed by https://github.com/opensha/opensha/pull/77/commits/9f7dfb209aa784b742842b0c3dfef33eeaceaa91

**Comment by chrisbc** [comment]
@voj I want to check impact of this on hazard if any

**Comment by voj** [comment]
@chrisbc The bug caused us to use `CaliforniaRegions.RELM_TESTING_GRIDDED` in the GridSourceProvider module. This meant that hazard calculation in effect always excluded background seismicity.

The new hazard integration test shows that the old expected values can now only be returned when background is excluded.
