### ISSUE TITLE
Issue: possible plotting errors (moguls)

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#137]
In recent inversion solutions we noticed differences in the MFD plots. Two view have 'moguls' while one view does not .... 

 (are these binning errors?)

The two PNG images below are for **Inversion Solution SW52ZXJzaW9uU29sdXRpb246MjE0MjguMFR6eGVZ** [view in Toshi](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/InversionSolution/SW52ZXJzaW9uU29sdXRpb246MjE0MjguMFR6eGVZ/InversionSolutionMfdTab)

Notice that we appear to have the same mogul effect in the dynamic plot which come out of our NZSHM InvesronRunner .

## Example **with moguls** 

![image](http://nzshm22-static-reports.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/SW52ZXJzaW9uU29sdXRpb246MjE0MjguMFR6eGVZ/solution_report/resources/hist_MAG_rates_log.png)

## Example without moguls from the same IS report...

![image](https://user-images.githubusercontent.com/8263318/151285685-ce0013cf-c02b-4aaa-874f-fe11681d2c41.png)

**Comment by voj** [comment]
note to self: 

```
		HistogramFunction magHist = solutionMagFreqHistogram(true);
		magHist.setName("solutionMFD_rateWeighted");
		appendMfdRows(magHist, rows, series);
		series++;
```

**Comment by voj** [comment]
Will be fixed upstream https://github.com/opensha/opensha/pull/83

**Comment by voj** [comment]
merged
