### ISSUE TITLE
Feature: build combined distributed + inversion model

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#139]
**As SRM team** we want to create a polygon-based distributed rate model built from:

 - an initial distributed rate model (e.g NZ hybrid)
 - a rupture set (with subsections & polygons)
 - relative weight for the new dist model (e.g 0.3 or  0.4)
 - a distance function. Where the distance from grid point to fault, scaled to the edge of the polygon decides the new rate on the background point (per grid location).

**so that** we can produce a new Distributed model to be used with Hazard calculations. Call this the **PolygonalDistributedRateModel** (file), where the rates within fault polygons are reduced according to:
 - fault polygons
 - the distance function / fn argument(s)
 - the weighting

As a simple starting point we will take the sum of all the grid points in each polygon and apply the function uniformly. This will lose any spatial variability (highs/low) for inidividual points within each polygon. 

> e.g for 0.3 DistWt, 0.7 FaultWt, then for FS rate = 1e-6 new FS rate  = 7e-7
> 
>  - initial on fault rate `OnFault1`
>  - `OnFault2 = FaultWeight *OnFault1`
>  - initial gridded polygon rate (sum of rates in polygon) `PolyGrid1`
>  - apply fn to Grid
>  - scale eact pt, so that new total `PolyGrid2 =  PolyGrid1 * DistWt`
>

**Comment by chrisbc** [comment]
For grid points in more than one fault polygon, take mean :)

 - **PolygonisedDistributedRateModelBuilder**, inputs are
     - rupture set
     - weight
     - fn
 - maybe an openquake format - or CSV ?

**Comment by voj** [comment]
@chrisbc Clarification questions:

I've implemented the pdf re-calculation as `oldValue * constantWeight * weightingFunction.apply(polygonWeights.getWeight(location)))` where `polygonWeights()` returns a number from 0 to 1 depending on how far the location is inside a section polygon from the fault trace. `weightingFunction` can modify the weight, currently only `LINEAR` (no change) is implemented.

- Is this what you expected?
- Also, I'm doing this for each point in the pdf, not just for the ones in section polygons. This means that all values outside section polygons are scaled by `constantWeight`. Is this expected?

**Comment by chrisbc** [comment]
@voj first part seems good but I don't think this is expected to operate on any grid values outside the polygons.

**Comment by chrisbc** [comment]
This way a value of BOXCAR and 0 would produce exactly what the current U3 setup is.

**Comment by voj** [comment]
@chrisbc if you choose LINEAR and a constant weight of 0.5, then all values inside polygons will be oldValue * 0.5 * polygonWeight.

And if you choose a constant value of 0, then all values inside polygons will be 0.

When I said that `LINEAR` is "no change", I meant it doesn't change the polygonWeight, so you get a linear distribution of weight in the polygon. I guess `IDENTITY` would be a better name for what it is. `LINEAR` is what it results in.

**Comment by voj** [comment]
This is what I understand we need to do:

- We want to scale the sum `S` of all `bs` grid point values in a fault polygon by `W` so that `S' = S * W`
- Each grid point is assigned a distance weight `D` so that
    - W = 1 / (exponent -1)
    - D = (distanceFromFault / poly-width) ^ exponent
- We calculate `S'` by scaling each `bs` proportionally to its `D`. Meaning that a `bs` with a `D` twice the size of the `D` of another `bs` is scaled twice as much.
- This means for each `bs` that `bs' = bs * W * D / SumOfAllD`

**Comment by voj** [comment]
merged
