### ISSUE TITLE
Feature: single reference magnitude for MFD uncertainty generation

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#158]
We want to use a single, constant reference magnitude when generating MFD uncertainty rather than the `minimize_below_mag` of each region

`minimize_below_mag` should still used when setting `stdDev`. Keep this code as is:
`double stdDev =
                    (mag < minimize_below_mag) ? 1.0 : firstWeightPower / Math.pow(rate,power-1);
`

but use `7.0` instead of `minimize_below_mag` in:
`double firstWeightPower = Math.pow(mfd.getClosestYtoX(minimize_below_mag), power-1);`

**Comment by voj** [comment]
@chrisdicaprio as discussed, I will add a precondition to assert that `minimize_below_mag` is <= than 7.0
