### ISSUE TITLE
FIX: Target MFD targetOnFaultSupraSeisMFD first bin has 0 rate

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#162]
Investigation by @chrisdicaprio  shows that the recent minMAG has a side effect of setting rate in first  on-Fault bin to zero ....

![image](https://user-images.githubusercontent.com/8263318/154820684-eb962ebc-4a5d-4ddf-8221-f00e279be197.png)

[Chris DiCaprio](https://app.slack.com/team/U02G6MGB8MT)  [9:59 PM]

> (https://nshmrevisionproject.slack.com/archives/D02GZK2MXU0/p1645261153811739)
> I got partway to figuring out why this is happening:
> NZSHM22_CrustalInversionTargetMFDs.init() creates the targetOnFaultSupraSeisMFDs by subtracting off trulyOffFaultMFD and totalSubSeismoOnFaultMFD. The subtraction of totalSubSeismoOnFaultMFD gives 0 in the bin that contains the minmag because the difference is <0 (subtractIncrementalMagFreqDist tests if the result is <0 and returns 0 for that bin if so).
> At that point, I'm stuck because I don't know how the code generates trulyOffFaultMFD and totalSubSeismoOnFaultMFD

**Comment by chrisbc** [comment]
@Voj here's that pic

![image](https://user-images.githubusercontent.com/8263318/154867478-91fdc88c-cb86-47e0-8c7f-dce9e1243f0f.png)

**Comment by voj** [comment]
Investigating the wobble in the solution between 6.5 and 7 in the chart that @chrisbc posted above:

As suspected, the turns in the wobble coincide with the TVZ target subseis:

![mfd_plot_NZ_TVZ_Target_MFDs](https://user-images.githubusercontent.com/3160916/154873445-7c7cb4fb-9559-467e-b965-ab5eb01f2d41.png)

![mfd_plot_NZ_SansTVZ_Target_MFDs](https://user-images.githubusercontent.com/3160916/154873451-636af154-dde4-4c16-8143-1dbf80132a5d.png)

Note how in my run the solution is also affected by the wobbles of the Sans TVZ target subseis.

The wobbles in the target subseis comes from the drop in sections with those min mags. Here are some histograms (magnitude, count):

-------------------NZ TVZ Gridded Region
6.55, 110
6.6499999999999995, 11
6.75, 13
6.85, 2

-------------------NZ RECTANGLE SANS TVZ Gridded Region
7.05, 1925
7.1499999999999995, 4
7.25, 2
7.35, 3
7.449999999999999, 4

The binning looks slightly different before the minMag QA changes but not fundamentally different:

-------------------NZ TVZ Gridded Region
6.449999999999999, 110
6.55, 8
6.6499999999999995, 16
6.75, 2

-------------------NZ RECTANGLE SANS TVZ Gridded Region
6.949999999999999, 1921
7.1499999999999995, 2
7.25, 3
7.35, 4
7.05, 8

**Comment by voj** [comment]
- totalTargetGR - trulyOffFaultMFD - totalSubSeismoOnFaultMFD is negative below a certain magnitude, meaning those values are clamped to 0
- It's not due to only trulyOffFaultMFD or totalSubSeismoOnFaultMFD. Both need to be subtracted from totalTargetGR
- There are faults of the zeroed-out magnitudes present in the data.
- This already happened before the minMag QA commit, just with slightly different bins

**Comment by chrisbc** [comment]
@voj , @chrisdicaprio & I discussed this with @mcg-gns ...

The simple replace all _clamped to 0_ values with a _very small value_ (1e-20) , so that our inversion MFD constraints behave as expected is an acceptable strategy here.
