### ISSUE TITLE
Feature: Make regional Maximum Magnitude an API argument

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#165]
SRM team want to experiment with forcing a upper bound on the maxMagnitude for Regional MFD. 

**NB** The current model (U3) is to calculate the maximum magnitude from the actual fault system ruptures (+ scaling relation)

Now we should take the user-defined max mag, and force the target for bins above max_mag to 1e-20.

**Comment by voj** [comment]
@chrisbc please clarify what impact this should have.

Currently, the regional maxMag is only used to populate a region's totalTargetGR bins:

```
// populate the MFD bins
double roundedMmaxOnFault=totalTargetGR.getX(totalTargetGR.getClosestXIndex(regionalRupSet.getMaxMag()));
totalTargetGR.setAllButTotMoRate(NZ_MIN_MAG,roundedMmaxOnFault,totalRateM5,bValue);
```

I'm assuming this maxMag should now be set manually.

Also, when we set everything below minMag to 1e-20, should we also set everything above maxMag to 1e-20?

Are there any other places where we need to enforce the new maxMag?

**Comment by voj** [comment]
merged
