### ISSUE TITLE
Feature: discriminate fault regions using CFM domain attribute

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#202]
Ref https://github.com/GNS-Science/nzshm-opensha/issues/199

Background: We have a number of situations where inversion configuration must have the region of a given Fault. As the project evolved, the concepts of TVZ (Taupo Volcanic Zone) and SansTVZ (not TVZ) regions emerged. This is applied to 
 - background/gridded seismicity models
 - Target MFD constraints
 - Slip rate constraints

In opensha the latter two applications require a (TVZ/Sans) decision at the level of a fault subsection, and up until now this decision was made geometrically using intersecting **fault section polygons** and **region polygons**.  This can lead to some subsection of a parent fault being TVZ while others are SANs - not ideal. Also using fault polygons (instead of fault trace) has the effect of including non-TVZ fault section into the TVZ (~14 section affected).

After consideration, the SRM team have agreed that an explicit definition of the fault region would be preferable and that whatever region is applied to a parent fault should apply to all its opensha subsections. And it turns out that in CFM we have the concept of Domain , where the domain 4: "Havre Trough - Taupo Rift" corresponds to the TVZ region.

**Comment by chrisbc** [comment]
In this ticket we're adding the fields domain_no and domain_name as attributes of each fault in the opensha XML format. We want to add a method that scales fault depth used to build rupture sets. Suggtested approach:

**Comment by voj** [comment]
slip rates are scaled based on regional polygons still. see `NZSHM22_InversionFaultSystemRuptSet.applySlipRateFactor()`
