### ISSUE TITLE
Feature: scale aveLowerDepth by Domain/Region

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#208]
SRM want the fields domain_no and domain_name as attributes of each fault in the opensha XML format.
Using #207  We want add methods to scale fault depth used to build rupture sets. 

Suggested approach:

In CrustalRuptureBuilder we add the following methods:
 - scaleDepthIncludeDomain(domainNo, scalar)
 - scaleDepthExcludeDomain(domainNo, scalar)

and in use this looks like....

```
builder = app.getCoulombRuptureSetBuilder()
tvzDomain =4 #TVZ

builder \
    .setFaultModel(ta["fault_model"])\
    .scaleDepthIncludeDomain(tvzDomain, 0.667)\ 
    .scaleDepthExcludeDomain(tvzDomain, 0.8)

....

```

_Originally posted by @chrisbc in https://github.com/GNS-Science/nzshm-opensha/issues/202#issuecomment-1066188881_

**Comment by voj** [comment]
merged
