### ISSUE TITLE
Fix: Otakiri aveLowerDepth

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#211]
This may be fixed by new CFM version, otherwise we may need to fix th StiffnessCalculator to handle tiny deptr OR just filter this fault out.

in the meantime we have a released jar from this branch commit https://github.com/GNS-Science/nzshm-opensha/commit/3a91c8961f516273d9808d466b30cac88b3ed2d7

FYI @voj @chrisdicaprio

**Comment by voj** [comment]
fixed with #213
