### ISSUE TITLE
Feature: New CFM_1_0A_ Fault models with min_depth filtering 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#213]
ref issue #211 where it turns out we need to filter out faults where aveLowerDepth < (3.9km ??)

 - [x] add 2 new XML files (@andy22b ) 
 - [x] update FM enumeration class (@voj)
    ```
    CFM_1_0A_DOM_ALL 
    CFM_1_0A_DOM_SANSTVZ 
    ```
 - [x] build named faults (@voj)
 - [x] new release jar @voj

**Comment by andy22b** [comment]
Addressed by https://github.com/GNS-Science/nzshm-opensha/pull/214

**Comment by voj** [comment]
all done
