### ISSUE TITLE
Fix: MFD table does not match diagnostics MFD plot

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#231]
The MFD plot created by the diagnostics report does not match the MFD table. See for example
http://simple-toshi-ui-test.s3-website-ap-southeast-2.amazonaws.com/InversionSolution/SW52ZXJzaW9uU29sdXRpb246MTAwMzkw

**Comment by chrisbc** [comment]
@chrisdicaprio I'll dig into this . The general MFD shape is  OK - but it looks like there low-rate/ empty bins (eg.7.45) in opensha plot (and I assume the solution/data) that are not visible in the dynamic plot.

**Comment by chrisbc** [comment]
So the table data is missing values ....
