### ISSUE TITLE
Feature: new deformation models

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#234]
We have new deformation models for Hikurangi and crustal.

### Crustal
file 1
- file: `slip_deficit_rates_no_prior_NZSHM22_RuptureSet-UnVwdHVyZUdlbmVyYXRpb25UYXNrOjEwMDAzOA==.dat`
- description: `geodetic, no geological prior constraint`
- compatibility: `rupture set RmlsZToxMDAwODc=`

file 2
- file: `slip_deficit_rates_with_prior_NZSHM22_RuptureSet-UnVwdHVyZUdlbmVyYXRpb25UYXNrOjEwMDAzOA==.dat`
- description: `geodetic, prior geological constraint`
- compatibility: `rupture set RmlsZToxMDAwODc=`

### Hikurangi
There are 5 trench creeping and 5 trench locked models.

Trench creeping are

- label: `SBD_0_2A_HKR_LR_30_M8[_CTP<N>]`
- description:  `Hikurangi, Kermadec to Louisville ridge, 30km - M7 to M8 corrected with slip deficit smoothed near east cape [perturbed<N>]`
- compatibility: `"FaultModel SBD_0_2_HKR_LR_30 and the next three deprecated ones, min mag 8"
- file names are self descriptive

Trench locked are same as trench creeping but label is
- `SBD_0_3_HKR_LR_30_M8<_LTP<N>`
- description includes `and locked near trench`
- compatibility: `FaultModel SBD_0_3_HKR_LR_30`

### Hikurangi EXP
There are 5 trench creeping and 5 trench locked
Trench creeping are
- label: `SBD_0_2A_HKR_LR_30_EXP_CTP<N>`
- description:  `Hikurangi, Kermadec to Louisville ridge, 30km - correlated noise [perturbed<N>]`
- compatibility: `"FaultModel SBD_0_2_HKR_LR_30 and the next three deprecated ones"
- file name `hk_trenchcreeping_exp_perturbation<N>.csv`

Trench locked follow the same pattern as above

**Comment by chrisdicaprio** [comment]
[deformation_models.zip](https://github.com/GNS-Science/nzshm-opensha/files/8578228/deformation_models.zip)

**Comment by voj** [comment]
@chrisdicaprio do you want the file `hk_eastcapesmoothed_PERTURBATION1.csv` as well? Its in the zip file but not in the issue description.

Also, could you please confirm the compatibility for Hikurangi EXP trench locked?
