### ISSUE TITLE
 Feature: Hikurangi deformation models

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#237]
There are 10 new deformation models for Hikurangi

# Trench Creeping
- file: `hik_trenchcreeping_exp_momentcorrected_perturbation<N>.csv`
- description:  `Hikurangi, Kermadec to Louisville ridge, 30km - correlated noise, M7 to M8 corrected with slip deficit smoothed near east cape [perturbed<N>]`
- label: `SBD_0_2A_HKR_LR_30_M8_EXP_CTP<N>`
- compatibility: `FaultModel SBD_0_2_HKR_LR_30 and the next three deprecated ones`

# Trench Locked
- file: `hik_trenchlocked_exp_momentcorrected_perturbation<N>.csv`
- description:  `Hikurangi, Kermadec to Louisville ridge, 30km - correlated noise, M7 to M8 corrected with slip deficit smoothed near east cape and locked near trench [perturbed<N>]`
- label: `SBD_0_3_HKR_LR_30_M8_EXP_LTP<N>`
- compatibility: `FaultModel SBD_0_2_HKR_LR_30 and the next three deprecated ones`

**Comment by chrisdicaprio** [comment]
here are the file
[def_models.zip](https://github.com/GNS-Science/nzshm-opensha/files/8647775/def_models.zip)
s

**Comment by voj** [comment]
closing as per @earjcr1
