### ISSUE TITLE
Investigate: why is UCERF3 code called

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#241]
why is `UCERF3InversionConfiguration.getSmoothStartingSolution` being called? Is it necessary?

We'd like to avoid calling, if possible, since the NZ inversions require a code change to this method that cannot be merged on the upstream fork

**Comment by voj** [comment]
History:
- the call has been there from the first version of the file
- it was simply commented out for a while https://github.com/GNS-Science/nzshm-opensha/commit/879420269cda5c2fa14c7fae027d8ce79d967227
- and then restored a few months later https://github.com/GNS-Science/nzshm-opensha/commit/a876e89ffc212eb20b6ef57dcdd8dd49db9aa9bb

This commit has this comment for adjustStartingModel:
```
 * CBC: cloned this from UCERF3InversionConfiguration just for testing with some water levels. It needs work to  
 * decided a) if its wanted and b) how it should work!! @MCG
