### ISSUE TITLE
May 12 modification to paleoearthquake timings input files for crustal inversions

### ISSUE THREAD

**Issue by earjcr1** [GNS-Science/nzshm-opensha#242]
Hi Oakley et al.,

There are two paleo-recurrence interval sites (Maruia 1 and 2) that are located at basically the boundary of Alpine Kaniere to Springs Junction and Alpine Springs Junction to Tophouse. The configuration of the CFM means that they are located on the latter, the NE side of the boundary, but scientifically they are more consistent with the SW side of the boundary (there is a fault junction and decrease in slip rates at the boundary, and they are consistent with the not-yet-decreased slip rates on the SW side). It was therefore decided to artificially move them 0.01* south and 0.015* west last Thursday so that the inversions would match them to Alpine Kaniere to Springs Junction. These updated paleo input files reflect that.

    GEOLOGIC_SLIP_MARUIA_MOVED(
            "Geologic timing, no TVZ, Maruia moved",
            "NZNSHM_paleotimings_GEOLOGICsliprates_moveitmoveit.txt"),

    GEODETIC_SLIP_MARUIA_MOVED(
            "Geodetic timing, no TVZ, Maruia moved",
            "NZNSHM_paleotimings_GEODETICsliprates_moveitmoveit.txt"),

    GEODETIC_SLIP_PRIOR_MARUIA_MOVED(
            "Geodetic with Geologic Prior timing, no TVZ, Maruia moved",
            "NZNSHM_paleotimings_GEODETICGEOLOGICPRIOR_moveitmoveit.txt"),

[NZNSHM_paleotimings_GEODETICGEOLOGICPRIOR_moveitmoveit.txt](https://github.com/GNS-Science/nzshm-opensha/files/8696157/NZNSHM_paleotimings_GEODETICGEOLOGICPRIOR_moveitmoveit.txt)
[NZNSHM_paleotimings_GEODETICsliprates_moveitmoveit.txt](https://github.com/GNS-Science/nzshm-opensha/files/8696158/NZNSHM_paleotimings_GEODETICsliprates_moveitmoveit.txt)
[NZNSHM_paleotimings_GEOLOGICsliprates_moveitmoveit.txt](https://github.com/GNS-Science/nzshm-opensha/files/8696159/NZNSHM_paleotimings_GEOLOGICsliprates_moveitmoveit.txt)

**Comment by voj** [comment]
@earjcr1 says this is not longer required
