### ISSUE TITLE
May 20 modification to paleoearthquake timings

### ISSUE THREAD

**Issue by earjcr1** [GNS-Science/nzshm-opensha#249]
GEOLOGIC_SLIP_MAY20CORRECTED(
        "Geologic timing, no TVZ, Maruia moved, May 20 corrections",
        "NZNSHM_paleotimings_GEOLOGIC_20May.txt"),

GEODETIC_SLIP_MAY20CORRECTED(
        "Geodetic timing, no TVZ, Maruia moved, May 20 corrections",
        "NZNSHM_paleotimings_GEODETIC_20May.txt"),

GEODETIC_GEOLOGICPRIOR_SLIP_MAY20CORRECTED(
        "Geodetic with Geologic Prior timing, no TVZ, Maruia moved, May 20 corrections",
        "NZNSHM_paleotimings_GEODETICGEOLOGICPRIOR_20May.txt"),

[NZNSHM_paleotimings_GEOLOGIC_20May.txt](https://github.com/GNS-Science/nzshm-opensha/files/8734547/NZNSHM_paleotimings_GEOLOGIC_20May.txt)
[NZNSHM_paleotimings_GEODETIC_20May.txt](https://github.com/GNS-Science/nzshm-opensha/files/8734548/NZNSHM_paleotimings_GEODETIC_20May.txt)
[NZNSHM_paleotimings_GEODETICGEOLOGICPRIOR_20May.txt](https://github.com/GNS-Science/nzshm-opensha/files/8734549/NZNSHM_paleotimings_GEODETICGEOLOGICPRIOR_20May.txt)

**Comment by voj** [comment]
replaced by #255
