### ISSUE TITLE
Feature: new spatial seis pdf

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#259]
Add a new seismicity grid pdf (attached)
`name`: `Floor_AddoptiEEPAScomb-CRU`
`shortName`: `hybridEEPAS`

file:
[Floor_AddoptiEEPAScomb-CRU_pdf.txt](https://github.com/GNS-Science/nzshm-opensha/files/8775469/Floor_AddoptiEEPAScomb-CRU_pdf.txt)

**Comment by voj** [comment]
merged
