### ISSUE TITLE
Feature: Python API support for Time Dependent models

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#269]
We want to process existing Inversion Solution to create TD Solutions where events rates are modified according to a selected  MRE resource file.

**Done when:**
 - [ ] API use sets input inversion solution
 - [ ] API user sets MRE resource file
 - [ ] API user sets other TD related arguments . @voj you know what these are ( eg open window etc)
 - [ ] Run produces a new TimeDependentInversionSOlution file with modified rates
 - [ ] the origiginal rates are retained in archived
 - [ ] write some metadata about the modifications  to a file (details to come)

**Comment by chrisbc** [comment]
FY*I @voj for scale3cd solutions we added a file WARNING.md to the solution with the following content ....

**Comment by chrisbc** [comment]
@voj Perhaps we can do something simlar - just to make sure the user is aware that the data is not 'as produced' in the inversion.

**Comment by voj** [comment]
merged
