### ISSUE TITLE
Oakley's Roundup

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#281]
- [x] describe flow through nzshm-opensha:
    - [x] archives and modules, which to use at which stage?
- [x] Configuration vs InputGenerator vs Runner
- [x] logic trees: implementation vs scientists' view vs upstream
- [x] ucerf3 dependencies vs creating copies
- [x] polygoniser?
- [x] reports?
- [x] hazard limitations?
- more strategic & historic stuff. eg. 
    -  [x] working with Kevin around NZ vs California vs the rest in the opensha codebase

**Comment by chrisbc** [comment]
Great work so far Oakley, just some minor suggestions:
 - [ ] some explanation of the docker image creation and how / why it publishes to AWS ECS 
 - [ ] add permalinks when referring to the codebase
 - [ ] **GNS-Science/nzshm-opensha** vs **opensha/opensha** - when to open upstream PRs
 - [ ] anything you'd have liked to do next time around ? ...

**Comment by voj** [comment]
merged
