### ISSUE TITLE
Explore: why is opensha UCERF3 function called

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-opensha#292]
Explore why `UCERF3InversionConfiguration.getSmoothStartingSolution` is called when running nzshm-opensha and if it can be avoided.

This function needed to be altered to work with the MFDs that the NZ NSHM uses, but cannot be altered in the upstream repo. Kevin thought that maybe we don't need to be calling the function at all. It is unknown (forgotten) if it is limited to a type of inversion (Puyseger, Hik, Crustal) or happens for all of them. It is unknown (forgotten) which inversion in particular required the modification to the function.

Can provide specific inversion parameters, if necessary.

**Comment by voj** [comment]
@chrisdicaprio it's currently only called for subduction inversion water level. 

See also the same investigation at https://github.com/GNS-Science/nzshm-opensha/issues/241

**Comment by voj** [comment]
Action to be taken: https://github.com/GNS-Science/nzshm-opensha/issues/294
