### ISSUE TITLE
Feature: reduce the fault polygon Mmin for Crustal TVZ

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#30]
TVZ MMin should be Mw 6.0. Only reduce the Mmin for TVZ, and for for the rest of the country please keep it at Mmin of 7.0.

 - [ ] refactor code to make intent clear
 - [ ] add API support so these values are inversion arguments, and make defaults the current values (7.0. 7.0)

**Comment by chrisbc** [comment]
Look like this supercedes #14

**Comment by voj** [comment]
@chrisbc we need to talk about the  `RupRateMinimizationConstraint` because that at the moment relies on a global minMag (and deep down on `U3SectionMFD_constraint` 😬 )
