### ISSUE TITLE
Investigate subduction range validity

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#317]
Part of #300 

Subduction clusters break the 'opensha' assumptions that sections in a cluster are consecutive. When building connections, the existing code often uses `SectIDRange` objects that reduce clusters or ruptures to the start and end section ids.

We want to investigate where this is a problem and what can be done to fix it.

**Comment by chrisdicaprio** [comment]
artefact of how joint ruptures were handled
