### ISSUE TITLE
FIX:  map/section_polygons.geojson incorrect for crustal solutions

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#38]
New inversion solution report with crustal solution [e.g. SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/InversionSolution/SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=) produces maps for CA instead of NZ. See participation section.

![](file:///home/chrisbc/DEV/GNS/opensha-new/AWS_S3_DATA/WORKING/SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=/solution_report/resources/sol_partic_supra_seis.png)

**Comment by chrisbc** [comment]
@voj possibly related: @andy22b has been looking at the modular inversions geojson and noted ...

> the section polygon geojson is the california section polygons, not the NZ ones

**Comment by voj** [comment]
Looks like all the geojson apart from fault_sections.geojson is for CA.

**Comment by voj** [comment]
fixed and merged into modular working branch
