### ISSUE TITLE
Epic: Integrate NZ paleo timing models with opensha

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#42]
SRM team want to use paleo timing constraints in inversions.

 - [x] get example from UCERF3 as guide to format
 - [x] #49
 - [x] #50
 - [x] https://github.com/GNS-Science/nzshm-runzi/issues/36

**Comment by voj** [comment]
Gave Chris R. the file used in `UCERF3_PaleoRateConstraintFetcher`
