### ISSUE TITLE
Feature: integrate NZ paleo timing rate data to opensha

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#49]
SRM want to run inversions using Paleo timing constraints.

**Done when**

 - [x] https://github.com/GNS-Science/nshm-paleo-db/blob/main/NZPaleoseismicSiteDB_v1.0.xlsx integrate with enum. reader etc so data is available for constraints

**Comment by chrisbc** [comment]
@voj data from @earjcr1  is now available here https://nshmrevisionproject.slack.com/archives/C02E5PXMB1D/p1637181658088700

**Comment by voj** [comment]
merged
