### ISSUE TITLE
Feature: implement/configure new Paleo timing constraint(s) for crustal inverstion

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#50]
SRM want crustal Inversions to use NZ paleo constraint data from new dataset

Integration of data is covered by #49 , this covers: 
 - [x] configuring the Inversion Constraint, 
 - [x] adding support to API for arguments (constraint weight at least)
 - [x] add test coverage as required
 - [x] Russ suggest there's also a weighting file that we may need to update for NZ - find and advise SRM team

**Comment by voj** [comment]
merged
