### ISSUE TITLE
Feature: Integrate NZ geodetic deformation models

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#51]
SRM want to use geodetic deformation models

Notes:
 - in UCERF3 both zeng* and neokinema* models in package data.erf.ucerf3.DeformationModels are geodetic models
 - Data provided by Kaj (see slack) should be checked to see if we're able to use it/transform it into the standard form above

**Done when:**
 - [ ] confirm name and shortnames for ENUM
 - [ ] added NZ Deformation models to project
 - [ ] API allows user to select new deformation model

**Comment by voj** [comment]
It looks like we might not have the data we need. UCERF3 files have the format
faultId.sectionId, lon1, lat1, lon2, lat2, slip, rake

while our files have
sectionId, faultId, , slip deficit rate (most probable rate), lower 95 confidence level, upper 95 confidence level 

Maybe the locations are not required. I'll see what they're used for.
