### ISSUE TITLE
Feature: Use Generalised Scaling Relation in RuptureSet and InversionSolutions

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#57]
SRM team want to compare new Scaling relation with others.

Done When:

 - [x] can configure Inversion scaling relationship via Java API
 - [x] option to recalc Magnitudes with new scaling relation 
 - [x] Add Java API support for extended arguments  on Generalised (Regime, EpistemicBound)
 - [ ] works for Crustal/Subduction and RuptureSet/Inversion.
 - [x] includes https://github.com/GNS-Science/nzshm-runzi/issues/25

#optionA
.setScalingRelationship(x)
.setScalingRelationship(x, recalc_mags = False, True)

**Comment by chrisbc** [comment]
@thingbaijam it looks like we must set either one or two arguments whenever we use the new class ssc.setRegime("interface"); 

e.g.

```
Stirling_2021_SimplifiedNZ_MagAreaRel ssc = new Stirling_2021_SimplifiedNZ_MagAreaRel();

ssc.setEpistemicBound("lower"); //use "lower" or "upper" 
ssc.setRegime("interface"); //use "interface" for subduction and anything else (e.g. "crustal" for non-interface regime.
```

So I imagine that  we'll want to run both rupture sets and inversions using the two different epistemic bounds?

**Comment by thingbaijam** [comment]
@chrisbc  Yes - we must set these two arguments for interface ruptures.
