### ISSUE TITLE
Feature: Range and Colourbar improvements to slip & participation plots 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#58]
SRM team

**want to** refine map visualisations used in Subduction inversions Diagnostic reports  - this covers both Participation and Slip plots

**so that** subtle differences are more easily spotted. 

 We need @mcg-gns input here to confirm specifics, but 
 - [ ] range split-point between plots are configurable
 - [ ] Colourbar/range for plots are improved

NB there may be interactions between these two changes, so they should probably be tried sequentially??

**Comment by chrisbc** [comment]
@mcg-gns is there still a need for this since we made the plot-filling mod?

**Comment by chrisdicaprio** [comment]
not addressing
