### ISSUE TITLE
Fix: Crustal targetMFDs must respect regional b-values for gridded-seismicity targets.

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#65]
We've shown in #64 the b-values in background targets are not handled  properly. We need to fix this so that:

 - [ ] regional b-values passed in to total targets are used for regional targets
 - [ ] slope of all targets form 5.0 to 7.0 is identical (same b-value)
 - [ ] subsection MFDs for the `totalSubSeismoOnFaultMFD_*` use the regional b-values

**Comment by voj** [comment]
using correct b-values has a subtle effect but does not seem to fix the problem (compare this to the plot in #64)
![mfd_plot_Total_Target_MFDs](https://user-images.githubusercontent.com/3160916/138175992-0dccf77b-ed0e-4683-8f4a-9ed707c327d8.png)
