### ISSUE TITLE
Investigate: Crustal Inversion slip vs Rupture rates

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#73]
SRM (Matt) want to know why we're seeing plots showing faults with some rate (in Solution) where there's a 0/mm Target slip rate in the Fault Model (+deformation).

**Update**
 - this is because these faults are not being filtered from CFM @mcg-gns is looking how this can be done and then new rupture sets can be produced where rupture do not exist. 
 - a second option @voj is looking at adding a ruptureSet filtering option to the inversion, where we drop all ruptures that have a 0-slip rate on any subsection. This done after applying the Deformation model allows for some more fluid exploration of deformation model vs rupture sets without letting these impossible ruptures enter the Inversion process. 
 
examples:

 - SW52ZXJzaW9uU29sdXRpb246MTI3MTguMDczb05G 

![image](https://user-images.githubusercontent.com/8263318/139769735-c0ee7a88-a7a6-4813-909c-328844e1cbb8.png)

**Comment by chrisbc** [comment]
@mcg-gns this was parked when we focussed on regional MFD setups. Is it still a concern?

**Comment by voj** [comment]
@chrisbc @mcg-gns the expectation is that this will be resolved with #90 

I think we can close this issue.
