### ISSUE TITLE
Review coursening vs thinning for subduction rupture building

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#8]
It seems we have some potential overlap between two methods of reducing the count of ruptures in subduction-zone rupture set . We should look at both methods and decide which we should use going forward . Maybe one method should be deprecated. 

NB this is not urgent as for now, we're OK with disabling both thinning and coarsening whilst we're working with 30km tiles.

- [ ] examine the difference between the  two approaches and explain them
- [ ] look for the root cause of the unexpected jump issue in size-coarsenenig in combo with aspect filter.
- [ ] decide on use-case/deprecation
- [ ] implement any change

**Comment by chrisdicaprio** [comment]
won't address
