### ISSUE TITLE
ReportPageGen: where did sa_progress_rate_dist.png disappear to?

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#99]
toshi expects the `sa_progress_rate_dist.png` file to exist in generated reports, but it is no longer there.

**Comment by voj** [comment]
It appears that since this commit https://github.com/opensha/opensha/commit/0b95517fb170b1a80aecca74f33d47d8787f586e , the file is called `rate_dist.png`

expected 
http://nzshm22-static-reports.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/SW52ZXJzaW9uU29sdXRpb246MTYyNDEuMHFnenRZ/solution_report/resources/sa_progress_rate_dist.png

actual
http://nzshm22-static-reports.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/SW52ZXJzaW9uU29sdXRpb246MTYyNDEuMHFnenRZ/solution_report/resources/rate_dist.png

@chrisbc is that the plot you would expect?

**Comment by chrisbc** [comment]
@voj can we raise a PR to revert this file name to the original? It may be that Kevin didn't think it'd affect us, this way we remind him that it does.

**Comment by voj** [comment]
Assigning myself so I don't forget to do it

**Comment by voj** [comment]
upstream PR https://github.com/opensha/opensha/pull/76

**Comment by chrisbc** [comment]
@voj did this get merged upsteam? - if so can you pls close this?

**Comment by voj** [comment]
@chrisbc it's not merged yet

**Comment by voj** [comment]
we decided it's no longer required
